// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace Mate_Production_AI
{
    public partial class Predict_IdleTimes
    {
        /// <summary>
        /// model input class for Predict_IdleTimes.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"NextIdleTime")]
            public float NextIdleTime { get; set; }

            [ColumnName(@"PrePreviousIdleTime")]
            public float PrePreviousIdleTime { get; set; }

            [ColumnName(@"PreviousIdleTime")]
            public float PreviousIdleTime { get; set; }

            [ColumnName(@"AverageIdleTime")]
            public float AverageIdleTime { get; set; }

            [ColumnName(@"CurrentAmount")]
            public float CurrentAmount { get; set; }

            [ColumnName(@"NewArrivaledOrders")]
            public float NewArrivaledOrders { get; set; }

            [ColumnName(@"OpenOrders")]
            public float OpenOrders { get; set; }

            [ColumnName(@"OverDueOrders")]
            public float OverDueOrders { get; set; }

            [ColumnName(@"ResourceUtilization")]
            public float ResourceUtilization { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for Predict_IdleTimes.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("Predict_IdleTimes.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
